import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# ════════════════════════════════════════════════════════════════════════
# STUB FUNCTIONS
# (Declared at the top, above all UI code. Each carries a docstring noting
#  what a teammate replaces it with in a later milestone.)
# ════════════════════════════════════════════════════════════════════════

@st.cache_data(ttl=60)
def run_climate_emulator(sst, rainfall, drought, heat, adapt_dict: dict) -> dict:
    """
    STUB — Teammate 1 replaces this with:
        model = joblib.load('models/crop_model.joblib')
        return model.predict(...)
    Returns dict with float values for 5 resilience indicators.
    """
    base = (sst / 3.5 * 0.4 + rainfall / 100 * 0.4 + drought / 12 * 0.2)
    bonus = (adapt_dict.get("crops", 0) * 0.08 +
             adapt_dict.get("gw", 0) * 0.06 +
             adapt_dict.get("irr", 0) * 0.07 +
             adapt_dict.get("water", 0) * 0.05)
    adj = max(0.0, min(1.0, base - bonus))
    return {
        "crop_yield_stability":     round((1 - adj) * 100, 1),
        "water_reservoir_security": round((1 - adj * 0.9) * 100, 1),
        "groundwater_stress":       round(adj * 100, 1),
        "agricultural_risk":        round(adj * 5, 2),
        "regional_resilience":      round((1 - adj) * 100, 1),
        "adjusted_risk_score":      adj
    }


def calculate_zscore(value, mean, std) -> float:
    """
    STUB — Teammate 3 replaces with utils.calculate_zscore()
    Standardizes a value against a reference mean/std distribution.
    """
    return round((value - mean) / std if std > 0 else 0, 2)


@st.cache_data(ttl=3600)
def load_policy_rules() -> dict:
    """
    STUB — Teammate 3 replaces with:
        import json
        return json.load(open('data/policy_rules.json'))
    Maps a risk tier to its recommended policy guidance string.
    """
    return {
        "Normal":         "Maintain standard monitoring. No immediate action required.",
        "Elevated Risk":  "Activate early-warning protocols. Review irrigation schedules.",
        "Severe Stress":  "Implement water rationing. Distribute drought-resistant seeds.",
        "Critical Alert": "Emergency response required. Activate all adaptation measures."
    }


def load_risk_thresholds() -> dict:
    """
    STUB — Teammate 3 replaces with risk_thresholds.json load.
    Defines the adjusted-risk-score boundaries between risk tiers.
    """
    return {"normal": 0.35, "elevated": 0.50, "severe": 0.70}


# ════════════════════════════════════════════════════════════════════════
# REPORT GENERATION (Milestone 3)
# ════════════════════════════════════════════════════════════════════════

def generate_txt_report(scenario: dict, results: dict,
                        top_strategy: dict, ood: bool) -> str:
    """
    Generates plain-text action briefing for download.
    Called by Milestone 3 export buttons.
    """
    from datetime import datetime
    active_adaptations = [
        k for k, v in scenario["adapt_dict"].items() if v
    ] or ["None selected"]

    return f"""
═══════════════════════════════════════════════════
AI CLIMATE RESILIENCE SANDBOX — ACTION BRIEFING
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M UTC")}
═══════════════════════════════════════════════════

SCENARIO PARAMETERS
───────────────────
Sea Surface Temperature Anomaly : {scenario["sst"]}°C
Monsoon Rainfall Deficit        : {scenario["rainfall"]}%
Drought Duration                : {scenario["drought"]} months
Heat Stress Index               : {scenario["heat"]} / 5

ADAPTATION MEASURES ACTIVE
──────────────────────────
{chr(10).join("  ✓ " + a for a in active_adaptations)}

KEY RISK INDICATORS
───────────────────
Crop Yield Stability       : {results["crop_yield_stability"]}%
Water Reservoir Security   : {results["water_reservoir_security"]}%
Groundwater Stress         : {results["groundwater_stress"]}%
Agricultural Risk Exposure : {results["agricultural_risk"]} / 5.0
Regional Resilience Score  : {results["regional_resilience"]}%

TOP RECOMMENDED STRATEGY
─────────────────────────
Strategies : {", ".join(top_strategy["strategies"]) or "None"}
Projected Resilience : {top_strategy["score"]}%

TRANSPARENCY NOTE
─────────────────
{"⚠️  OUT-OF-DISTRIBUTION: Scenario exceeds training range (1982–2022)." if ood else "✅  Scenario within historical training range (1982–2022)."}
Model: Random Forest Regressor | Training period: 1982–2022

───────────────────────────────────────────────────
DISCLAIMER
This briefing is generated by an AI surrogate model for
scenario planning purposes only. It does not constitute
an operational forecast or official government guidance.
═══════════════════════════════════════════════════
"""


def generate_pdf_report(scenario: dict, results: dict,
                        top_strategy: dict, ood: bool) -> bytes:
    """
    Generates PDF action briefing for download.
    Returns bytes for st.download_button.
    """
    from fpdf import FPDF
    from datetime import datetime

    pdf = FPDF()
    pdf.add_page()

    # Header bar
    pdf.set_fill_color(26, 107, 107)   # teal #1a6b6b
    pdf.rect(0, 0, 210, 22, "F")
    pdf.set_font("Helvetica", "B", 14)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(10, 6)
    pdf.cell(0, 10, "AI Climate Resilience Sandbox - Action Briefing")

    # Date
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(200, 240, 240)
    pdf.set_xy(10, 15)
    pdf.cell(0, 6,
             f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}")

    # Reset text color
    pdf.set_text_color(30, 30, 30)
    pdf.set_y(28)

    # OOD warning box (if triggered)
    if ood:
        pdf.set_fill_color(254, 226, 226)
        pdf.set_draw_color(220, 38, 38)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(153, 27, 27)
        pdf.multi_cell(
            0, 7,
            "OUT-OF-DISTRIBUTION WARNING: Parameters exceed training "
            "range. Interpret results as exploratory estimates only.",
            border=1, fill=True,
        )
        pdf.set_text_color(30, 30, 30)
        pdf.ln(3)

    # Section helper
    def section(title):
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_fill_color(240, 253, 250)
        pdf.set_text_color(26, 107, 107)
        pdf.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT", fill=True)
        pdf.set_text_color(30, 30, 30)
        pdf.set_font("Helvetica", "", 10)
        pdf.ln(1)

    # Row helper
    def row(label, value, unit=""):
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(90, 7, label)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 7, f"{value}{unit}", new_x="LMARGIN", new_y="NEXT")

    # Scenario Parameters
    section("SCENARIO PARAMETERS")
    row("SST Anomaly",        scenario["sst"],      " C")
    row("Rainfall Deficit",   scenario["rainfall"], "%")
    row("Drought Duration",   scenario["drought"],  " months")
    row("Heat Stress Index",  scenario["heat"],     " / 5")
    pdf.ln(3)

    # Adaptation Measures
    section("ADAPTATION MEASURES ACTIVE")
    active = [k for k, v in scenario["adapt_dict"].items() if v]
    names = {
        "crops": "Drought-Resistant Crop Program",
        "gw":    "Emergency Groundwater Rationing",
        "irr":   "Supplemental Irrigation Support",
        "water": "Water Conservation Initiative",
    }
    if active:
        for k in active:
            pdf.cell(0, 7, f"  -  {names[k]}", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.cell(0, 7, "  No measures active", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Key Risk Indicators
    section("KEY RISK INDICATORS")
    row("Crop Yield Stability",       results["crop_yield_stability"],     "%")
    row("Water Reservoir Security",   results["water_reservoir_security"], "%")
    row("Groundwater Stress",         results["groundwater_stress"],       "%")
    row("Agricultural Risk Exposure", results["agricultural_risk"],        " / 5.0")
    row("Regional Resilience Score",  results["regional_resilience"],      "%")
    pdf.ln(3)

    # Top Strategy
    section("TOP RECOMMENDED STRATEGY")
    strats = ", ".join(top_strategy["strategies"]) or "None"
    pdf.multi_cell(0, 7, f"Strategies: {strats}")
    row("Projected Resilience",       top_strategy["score"],               "%")
    pdf.ln(3)

    # Disclaimer
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.multi_cell(
        0, 5,
        "DISCLAIMER: This briefing is generated by an AI surrogate model "
        "for scenario planning purposes only. It does not constitute an "
        "operational forecast or official government guidance.",
    )

    return bytes(pdf.output())


# ════════════════════════════════════════════════════════════════════════
# SESSION STATE INITIALIZATION
# (Must run before any other st.* calls so widget keys have defaults.)
# ════════════════════════════════════════════════════════════════════════

defaults = {
    "sst_anomaly":       1.5,
    "rainfall_deficit":  30,
    "drought_months":    3,
    "heat_stress":       2,
    "adapt_crops":       False,
    "adapt_groundwater": False,
    "adapt_irrigation":  False,
    "adapt_water":       False,
    "active_preset":     "custom",
}
for key, val in defaults.items():
    if key not in st.session_state:
        st.session_state[key] = val


# ════════════════════════════════════════════════════════════════════════
# 1. PAGE CONFIG
# ════════════════════════════════════════════════════════════════════════

st.set_page_config(
    page_title="AI Climate Resilience Sandbox",
    page_icon="🌍",
    layout="wide",
    # "auto" keeps the sidebar expanded on desktop but collapses it on
    # narrow/mobile viewports so the dashboard isn't buried behind it.
    initial_sidebar_state="auto",
)


# ════════════════════════════════════════════════════════════════════════
# GLOBAL CSS
# ════════════════════════════════════════════════════════════════════════

st.markdown(
    """
    <style>
    /* ---- Risk color variables + theme tokens ---- */
    :root {
        --color-primary:  #1a6b6b;   /* deep teal */
        --color-normal:   #16a34a;   /* green   */
        --color-elevated: #ca8a04;   /* yellow  */
        --color-severe:   #ea580c;   /* orange  */
        --color-critical: #dc2626;   /* red     */
    }

    /* ---- App background: white ---- */
    .stApp {
        background-color: #ffffff;
    }

    /* ---- Sidebar background: very light teal ---- */
    section[data-testid="stSidebar"] {
        background-color: #f0fdfa;
    }

    /* ---- Card container ---- */
    .crs-card {
        background-color: #ffffff;
        border-radius: 0.625rem;                  /* 10px */
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.07);
        padding: 1.1rem 1.4rem;
        margin: 0.6rem 0 1rem 0;
        border: 1px solid #e2e8f0;
    }

    /* ---- Header bar (row 1) ---- */
    .crs-header {
        display: flex;
        align-items: center;
        justify-content: space-between;
        background-color: var(--color-primary);
        border-radius: 0.625rem 0.625rem 0 0;
        padding: 1.1rem 1.5rem;
    }
    .crs-header h1 {
        color: #ffffff;
        font-weight: 700;
        font-size: 1.75rem;
        margin: 0;
        line-height: 1.2;
    }
    .crs-badge {
        background-color: var(--color-normal);
        color: #ffffff;
        font-size: 0.85rem;
        font-weight: 600;
        padding: 0.35rem 0.9rem;
        border-radius: 999px;
        white-space: nowrap;
    }

    /* ---- Disclaimer bar (row 2, amber) ---- */
    .crs-disclaimer {
        background-color: #fef3c7;
        color: #92400e;
        font-size: 0.85rem;
        font-style: italic;
        padding: 0.6rem 1.5rem;
        border-radius: 0 0 0.625rem 0.625rem;
        border: 1px solid #fde68a;
        margin-bottom: 1rem;
    }

    /* ---- Scenario summary styling ---- */
    .crs-summary-climate {
        font-size: 1.05rem;
        font-weight: 600;
        color: var(--color-primary);
        margin-bottom: 0.4rem;
    }
    .crs-summary-adapt {
        font-size: 0.95rem;
        color: #334155;
    }
    .crs-preset-pill {
        display: inline-block;
        background-color: var(--color-primary);
        color: #ffffff;
        font-size: 0.8rem;
        font-weight: 600;
        padding: 0.3rem 0.85rem;
        border-radius: 999px;
        margin-top: 0.6rem;
    }

    /* ---- Placeholder block ---- */
    .crs-placeholder {
        text-align: center;
        color: #64748b;
        font-size: 1.1rem;
        padding: 3rem 1rem;
        border: 2px dashed #cbd5e1;
        border-radius: 0.625rem;
        margin-top: 1.5rem;
    }

    /* ---- Preset button styling (severity-colored) ---- */
    /* Streamlit renders buttons in column order; we color them by position. */
    section[data-testid="stSidebar"] div[data-testid="column"]:nth-of-type(1) button {
        background-color: var(--color-normal);
        color: #ffffff;
        border: none;
    }
    section[data-testid="stSidebar"] div[data-testid="column"]:nth-of-type(2) button {
        background-color: var(--color-severe);
        color: #ffffff;
        border: none;
    }
    section[data-testid="stSidebar"] div[data-testid="column"]:nth-of-type(3) button {
        background-color: var(--color-critical);
        color: #ffffff;
        border: none;
    }
    section[data-testid="stSidebar"] div[data-testid="column"] button:hover {
        filter: brightness(1.08);
        color: #ffffff;
    }

    /* ---- Hide default Streamlit footer + hamburger menu ---- */
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    header[data-testid="stHeader"] {background: transparent;}

    /* ---- Mobile-safe: base font in rem ---- */
    html, body, [class*="css"] {
        font-size: 1rem;
    }

    /* ---- Mobile responsive polish ---- */
    @media (max-width: 768px) {
        /* Stack metric cards vertically */
        [data-testid="column"] {
            min-width: 100% !important;
            margin-bottom: 0.5rem;
        }
        /* Reduce header font size */
        h1 { font-size: 1.3rem !important; }
        h2 { font-size: 1.1rem !important; }
        /* Smaller padding on cards */
        .card-container, .crs-card { padding: 10px !important; }
        /* Hide map legend on very small screens */
        .map-legend { display: none; }
        /* Full-width export buttons */
        .stDownloadButton > button { width: 100% !important; }
    }
    </style>
    """,
    unsafe_allow_html=True,
)


# ════════════════════════════════════════════════════════════════════════
# PRESET DEFINITIONS
# ════════════════════════════════════════════════════════════════════════

MODERATE_EL_NINO = {"sst_anomaly": 1.2, "rainfall_deficit": 20, "drought_months": 2,  "heat_stress": 2}
SEVERE_DROUGHT   = {"sst_anomaly": 2.0, "rainfall_deficit": 55, "drought_months": 6,  "heat_stress": 3}
EXTREME_ENSO     = {"sst_anomaly": 3.2, "rainfall_deficit": 85, "drought_months": 10, "heat_stress": 5}

PRESET_LABELS = {
    "moderate_el_nino":  "Moderate El Niño",
    "severe_drought":    "Severe Drought",
    "extreme_enso":      "Extreme ENSO Shock",
}


def _apply_preset(preset: dict, preset_name: str) -> None:
    """Load a preset's values into session_state.

    Used as an on_click callback. Callbacks run BEFORE widgets are
    re-instantiated on the rerun, so writing to widget-keyed session_state
    here is allowed (writing it during the main script body is not).
    """
    for key, val in preset.items():
        st.session_state[key] = val
    st.session_state["active_preset"] = preset_name


def _reset_defaults() -> None:
    """Restore all sliders/checkboxes to their default values (on_click callback)."""
    for key, val in defaults.items():
        st.session_state[key] = val
    st.session_state["active_preset"] = "custom"


# ════════════════════════════════════════════════════════════════════════
# 4. LEFT SIDEBAR
# ════════════════════════════════════════════════════════════════════════

with st.sidebar:
    # ── Logo / title ───────────────────────────────────────────────
    st.markdown("### 🌍 Climate Resilience Sandbox")
    st.markdown("---")

    # ── Climate scenario inputs ────────────────────────────────────
    st.subheader("🌡️ Climate Scenario Inputs")

    sst_anomaly = st.slider(
        "Sea Surface Temperature Anomaly (°C)",
        min_value=0.0, max_value=3.5, step=0.1,
        value=st.session_state["sst_anomaly"],
        key="sst_anomaly",
        help="SST anomaly above baseline. >2.5°C = extreme El Niño.",
    )

    rainfall_deficit = st.slider(
        "Monsoon Rainfall Deficit (%)",
        min_value=0, max_value=100, step=1,
        value=st.session_state["rainfall_deficit"],
        key="rainfall_deficit",
        help="Reduction in expected seasonal monsoon rainfall.",
    )

    drought_months = st.slider(
        "Drought Duration (months)",
        min_value=0, max_value=12, step=1,
        value=st.session_state["drought_months"],
        key="drought_months",
        help="Consecutive months of below-normal rainfall.",
    )

    heat_stress = st.slider(
        "Heat Stress Index (1–5)",
        min_value=1, max_value=5, step=1,
        value=st.session_state["heat_stress"],
        key="heat_stress",
        help="1=Mild  2=Low  3=Moderate  4=High  5=Extreme",
    )

    # ── Adaptation strategy controls ───────────────────────────────
    st.subheader("🌾 Adaptation Measures")

    adapt_crops = st.checkbox(
        "Drought-Resistant Crop Program",
        value=st.session_state["adapt_crops"],
        key="adapt_crops",
        help="Short-cycle, drought-tolerant seed deployment.",
    )
    adapt_groundwater = st.checkbox(
        "Emergency Groundwater Rationing",
        value=st.session_state["adapt_groundwater"],
        key="adapt_groundwater",
        help="Volumetric water-use limits across irrigation zones.",
    )
    adapt_irrigation = st.checkbox(
        "Supplemental Irrigation Support",
        value=st.session_state["adapt_irrigation"],
        key="adapt_irrigation",
        help="Activate supplemental micro-irrigation infrastructure.",
    )
    adapt_water = st.checkbox(
        "Water Conservation Initiative",
        value=st.session_state["adapt_water"],
        key="adapt_water",
        help="Community rainwater harvesting and conservation.",
    )

    # ── Quick scenario presets ─────────────────────────────────────
    st.subheader("🚀 Quick Presets")

    col1, col2, col3 = st.columns(3)
    with col1:
        st.button("🌤 Moderate", use_container_width=True,
                  on_click=_apply_preset, args=(MODERATE_EL_NINO, "moderate_el_nino"))
    with col2:
        st.button("🔥 Severe", use_container_width=True,
                  on_click=_apply_preset, args=(SEVERE_DROUGHT, "severe_drought"))
    with col3:
        st.button("⚡ Extreme", use_container_width=True,
                  on_click=_apply_preset, args=(EXTREME_ENSO, "extreme_enso"))

    st.button("↺ Reset to Default", use_container_width=True,
              on_click=_reset_defaults)

    # ── About ──────────────────────────────────────────────────────
    with st.expander("ℹ️ About this tool"):
        st.markdown(
            """
            **AI Climate Resilience Sandbox** is a web-based decision-support
            platform for exploring extreme El Niño–Southern Oscillation (ENSO)
            climate scenarios and comparing adaptation strategies.

            **Target users:** District administrators, agricultural cooperatives,
            water management boards, rural development agencies, and climate NGOs.

            **Note:** This platform is for scenario planning only. It does not
            provide authoritative forecasts and should not replace operational
            weather or emergency-management guidance.
            """
        )


# ════════════════════════════════════════════════════════════════════════
# 2. HEADER BANNER + DISCLAIMER
# ════════════════════════════════════════════════════════════════════════

st.markdown(
    """
    <div class="crs-header">
        <h1>🌍&nbsp; AI Climate Resilience Sandbox</h1>
        <span class="crs-badge">SDG 13: Climate Action</span>
    </div>
    <div class="crs-disclaimer">
        ⚠️ Decision-support tool only — not an operational forecast.
        All results are exploratory scenario estimates.
    </div>
    """,
    unsafe_allow_html=True,
)


# ════════════════════════════════════════════════════════════════════════
# 5. SCENARIO SUMMARY BAR
# ════════════════════════════════════════════════════════════════════════

climate_desc = (
    f"SST +{sst_anomaly}°C  |  "
    f"{rainfall_deficit}% Rainfall Deficit  |  "
    f"{drought_months} Month Drought  |  "
    f"Heat Level {heat_stress}/5"
)

active_adaptations = [
    name for name, active in {
        "Drought-Resistant Crops": adapt_crops,
        "Groundwater Rationing":   adapt_groundwater,
        "Supplemental Irrigation": adapt_irrigation,
        "Water Conservation":      adapt_water,
    }.items() if active
]

adapt_desc = (
    "Adaptations Active: " + ", ".join(active_adaptations)
    if active_adaptations else "⚠️ No adaptation measures active"
)

preset_pill_html = ""
if st.session_state["active_preset"] != "custom":
    preset_label = PRESET_LABELS.get(st.session_state["active_preset"], "Custom")
    preset_pill_html = f'<div class="crs-preset-pill">Preset: {preset_label}</div>'

st.markdown(
    f"""
    <div class="crs-card">
        <div class="crs-summary-climate">📋&nbsp; {climate_desc}</div>
        <div class="crs-summary-adapt">{adapt_desc}</div>
        {preset_pill_html}
    </div>
    """,
    unsafe_allow_html=True,
)


# ════════════════════════════════════════════════════════════════════════
# MAIN AREA — DASHBOARD (MILESTONE 2)
# ════════════════════════════════════════════════════════════════════════

# ---- Compute all values once at the top of the main rendering block ----
adapt_dict = {
    "crops": int(st.session_state.adapt_crops),
    "gw":    int(st.session_state.adapt_groundwater),
    "irr":   int(st.session_state.adapt_irrigation),
    "water": int(st.session_state.adapt_water),
}

results = run_climate_emulator(
    st.session_state.sst_anomaly,
    st.session_state.rainfall_deficit,
    st.session_state.drought_months,
    st.session_state.heat_stress,
    adapt_dict,
)

baseline = run_climate_emulator(
    st.session_state.sst_anomaly,
    st.session_state.rainfall_deficit,
    st.session_state.drought_months,
    st.session_state.heat_stress,
    {"crops": 0, "gw": 0, "irr": 0, "water": 0},
)

adj = results["adjusted_risk_score"]
policy_rules = load_policy_rules()


# ════════════════════════════════════════════════════════════════════════
# SECTION A — INLINE STATUS ALERT
# ════════════════════════════════════════════════════════════════════════

# Rule 1 — Out-of-Distribution warning (highest priority)
if (st.session_state.sst_anomaly > 3.0
        or st.session_state.rainfall_deficit > 80
        or st.session_state.drought_months > 10
        or st.session_state.heat_stress == 5):
    st.error(
        "⚠️ Out-of-Distribution Warning: One or more parameters exceed "
        "the model's historical training range (1982–2022). Results are "
        "exploratory estimates only — interpret with caution."
    )

# Rule 2 — Risk level status (always shown)
if adj >= 0.70:
    st.error("🔴 Critical Resource Alert — " + policy_rules["Critical Alert"])
elif adj >= 0.50:
    st.warning("🟠 Severe Stress — " + policy_rules["Severe Stress"])
elif adj >= 0.35:
    st.warning("🟡 Elevated Risk — " + policy_rules["Elevated Risk"])
else:
    st.success("🟢 Normal Conditions — " + policy_rules["Normal"])


# ════════════════════════════════════════════════════════════════════════
# SECTION B — FIVE METRIC CARDS
# ════════════════════════════════════════════════════════════════════════

st.subheader("📊 Key Resilience Indicators")


def _status_higher_better(value):
    """Status tier for metrics where higher = better."""
    if value >= 70:
        return "Normal", "#16a34a"
    elif value >= 50:
        return "Elevated", "#ca8a04"
    elif value >= 30:
        return "Severe", "#ea580c"
    return "Critical", "#dc2626"


def _status_gw_stress(value):
    """Status tier for groundwater stress (lower = better)."""
    if value <= 30:
        return "Normal", "#16a34a"
    elif value <= 50:
        return "Elevated", "#ca8a04"
    elif value <= 69:
        return "Severe", "#ea580c"
    return "Critical", "#dc2626"


def _status_ag_risk(value):
    """Status tier for agricultural risk on a 0–5 scale (lower = better)."""
    if value <= 1.5:
        return "Normal", "#16a34a"
    elif value <= 2.5:
        return "Elevated", "#ca8a04"
    elif value <= 3.5:
        return "Severe", "#ea580c"
    return "Critical", "#dc2626"


# Each metric definition: label, value, baseline, unit, delta_color, status fn
metric_defs = [
    {
        "label": "🌾 Crop Yield Stability",
        "value": results["crop_yield_stability"],
        "base":  baseline["crop_yield_stability"],
        "unit":  "%",
        "delta_color": "normal",
        "status_fn": _status_higher_better,
    },
    {
        "label": "💧 Water Reservoir Security",
        "value": results["water_reservoir_security"],
        "base":  baseline["water_reservoir_security"],
        "unit":  "%",
        "delta_color": "normal",
        "status_fn": _status_higher_better,
    },
    {
        "label": "🏜 Groundwater Stress",
        "value": results["groundwater_stress"],
        "base":  baseline["groundwater_stress"],
        "unit":  "%",
        "delta_color": "inverse",
        "status_fn": _status_gw_stress,
    },
    {
        "label": "⚠️ Agricultural Risk Exposure",
        "value": results["agricultural_risk"],
        "base":  baseline["agricultural_risk"],
        "unit":  "/ 5.0",
        "delta_color": "inverse",
        "status_fn": _status_ag_risk,
    },
    {
        "label": "🛡 Regional Resilience Score",
        "value": results["regional_resilience"],
        "base":  baseline["regional_resilience"],
        "unit":  "%",
        "delta_color": "normal",
        "status_fn": _status_higher_better,
    },
]

# Styled card container that actually wraps the 5 columns. A bordered
# st.container nests the columns in the DOM, unlike a bare <div> markdown
# (which Streamlit renders as a separate, empty element).
with st.container(border=True):
    metric_cols = st.columns(5)
    for col, m in zip(metric_cols, metric_defs):
        delta = m["value"] - m["base"]
        status_label, status_color = m["status_fn"](m["value"])
        with col:
            st.metric(
                label=m["label"],
                value=f"{m['value']}{m['unit']}",
                delta=f"{delta:+.1f}{m['unit']}",
                delta_color=m["delta_color"],
            )
            st.markdown(
                f'<span style="background:{status_color};color:white;'
                f'padding:2px 10px;border-radius:12px;font-size:0.75rem;'
                f'font-weight:600;">{status_label}</span>',
                unsafe_allow_html=True,
            )


# ════════════════════════════════════════════════════════════════════════
# SECTION C — TWO-COLUMN LAYOUT (Risk Map + Recommendations)
# ════════════════════════════════════════════════════════════════════════

left_col, right_col = st.columns([1.4, 1], gap="large")

# ── LEFT: INTERACTIVE RISK MAP ──────────────────────────────────────────
with left_col:
    st.subheader("📍 Regional Risk Distribution")

    DISTRICTS = [
        {"name": "Northern Plains",    "lat": 22.5, "lon": 78.0},
        {"name": "Central Valley",     "lat": 21.0, "lon": 77.5},
        {"name": "Eastern Hills",      "lat": 21.5, "lon": 80.0},
        {"name": "Southern Delta",     "lat": 19.0, "lon": 77.0},
        {"name": "Western Plateau",    "lat": 20.5, "lon": 75.5},
        {"name": "Coastal Zone",       "lat": 18.0, "lon": 73.5},
        {"name": "Mountain Foothills", "lat": 23.0, "lon": 79.5},
        {"name": "Inland Basin",       "lat": 20.0, "lon": 76.0},
    ]
    OFFSETS = [0.10, -0.12, 0.08, -0.15, 0.05, -0.09, 0.13, -0.07]

    RISK_COLOR_MAP = {
        "Normal":         "#16a34a",
        "Elevated Risk":  "#ca8a04",
        "Severe Stress":  "#ea580c",
        "Critical Alert": "#dc2626",
    }

    map_rows = []
    for i, d in enumerate(DISTRICTS):
        risk_i = max(0.0, min(1.0, adj + OFFSETS[i]))
        if risk_i >= 0.70:
            risk_label_i = "Critical Alert"
        elif risk_i >= 0.50:
            risk_label_i = "Severe Stress"
        elif risk_i >= 0.35:
            risk_label_i = "Elevated Risk"
        else:
            risk_label_i = "Normal"
        resilience_i = round((1 - risk_i) * 100, 1)
        map_rows.append({
            "District":            d["name"],
            "lat":                 d["lat"],
            "lon":                 d["lon"],
            "Risk Level":          risk_label_i,
            "Resilience Score (%)": resilience_i,
            "size":                18,
        })

    map_df = pd.DataFrame(map_rows)

    try:
        # Use the modern MapLibre-based map (px.scatter_map). The older
        # px.scatter_mapbox renderer is deprecated in Plotly 6.x and its
        # zoom/pan/modebar controls misbehave.
        fig_map = px.scatter_map(
            map_df,
            lat="lat",
            lon="lon",
            color="Risk Level",
            color_discrete_map=RISK_COLOR_MAP,
            size="size",
            size_max=18,
            hover_name="District",
            hover_data={
                "Risk Level": True,
                "Resilience Score (%)": True,
                "lat": False,
                "lon": False,
                "size": False,
            },
            zoom=5,
            center={"lat": 21, "lon": 77.5},
            height=420,
        )
        fig_map.update_layout(
            map_style="carto-positron",
            margin={"l": 0, "r": 0, "t": 0, "b": 0},
            legend_title_text="Risk Level",
        )
        st.plotly_chart(
            fig_map,
            use_container_width=True,
            # scrollZoom enables mouse-wheel zoom; a stable key preserves the
            # user's zoom/pan across the reruns triggered by slider changes.
            config={"scrollZoom": True, "displaylogo": False},
            key="risk_map",
        )
    except Exception:
        # FALLBACK: treemap when mapbox is unavailable.
        fig_tree = px.treemap(
            map_df,
            path=["District"],
            values=[1] * len(map_df),
            color="Resilience Score (%)",
            color_continuous_scale=["#dc2626", "#ca8a04", "#16a34a"],
            hover_data={"Risk Level": True, "Resilience Score (%)": True},
            height=420,
        )
        fig_tree.update_layout(margin={"l": 0, "r": 0, "t": 0, "b": 0})
        st.plotly_chart(
            fig_tree, use_container_width=True,
            config={"displaylogo": False}, key="risk_map",
        )

    st.markdown(
        "🟢 Normal&nbsp;&nbsp; 🟡 Elevated Risk&nbsp;&nbsp; "
        "🟠 Severe Stress&nbsp;&nbsp; 🔴 Critical Alert"
    )

# ── RIGHT: STRATEGY RECOMMENDATIONS ─────────────────────────────────────
with right_col:
    st.subheader("🏆 Recommended Strategies")

    STRATEGY_DESCRIPTIONS = {
        frozenset(["crops", "water"]):
            "Reduces crop failure while preserving groundwater. "
            "Effective for moderate droughts.",
        frozenset(["crops", "gw", "irr", "water"]):
            "Maximum resilience. Requires significant coordination "
            "and resources across all sectors.",
        frozenset(["gw", "irr"]):
            "Balances short-term water access with long-term "
            "aquifer health.",
        frozenset(["crops", "gw"]):
            "Cost-effective pairing for early-stage drought response.",
        frozenset(["irr", "water"]):
            "Strong for water security; moderate crop protection.",
    }
    DEFAULT_DESC = ("Moderate improvement. Consider pairing with "
                    "additional measures for stronger outcomes.")

    STRATEGY_NAMES = {
        "crops": "Drought-Resistant Crops",
        "gw":    "Groundwater Rationing",
        "irr":   "Supplemental Irrigation",
        "water": "Water Conservation",
    }

    # Evaluate all 16 combinations of adaptation measures.
    all_combos = []
    with st.spinner("Calculating..."):
        for c in range(16):
            combo = {
                "crops": bool(c & 1),
                "gw":    bool(c & 2),
                "irr":   bool(c & 4),
                "water": bool(c & 8),
            }
            result_c = run_climate_emulator(
                st.session_state.sst_anomaly,
                st.session_state.rainfall_deficit,
                st.session_state.drought_months,
                st.session_state.heat_stress,
                {k: int(v) for k, v in combo.items()},
            )
            all_combos.append({
                "combo": combo,
                "score": result_c["regional_resilience"],
                "adj":   result_c["adjusted_risk_score"],
            })

    top3 = sorted(all_combos, key=lambda x: x["score"], reverse=True)[:3]

    RANK_BADGES = ["🥇", "🥈", "🥉"]
    RANK_LABELS = ["Best Strategy", "Runner-Up", "Third Option"]

    active_keys = frozenset(k for k, v in adapt_dict.items() if v)

    for i, item in enumerate(top3):
        active_in_combo = [
            STRATEGY_NAMES[k] for k, v in item["combo"].items() if v
        ]
        combo_keys = frozenset(k for k, v in item["combo"].items() if v)
        desc = STRATEGY_DESCRIPTIONS.get(combo_keys, DEFAULT_DESC)
        is_active = (combo_keys == active_keys)

        border = "3px solid #0d9488" if is_active else "1px solid #ccfbf1"
        bg = "#f0fdfa" if is_active else "#ffffff"

        chips = "  ".join(
            f'<span style="background:#dcfce7;color:#166534;'
            f'padding:2px 8px;border-radius:10px;font-size:0.75rem;'
            f'margin-right:4px;">✅ {s}</span>'
            for s in (active_in_combo or ["No measures"])
        )
        active_note = (
            "<div style='color:#0d9488;font-size:0.75rem;'>← Currently Active</div>"
            if is_active else ""
        )

        st.markdown(
            f"""
            <div style="border:{border};background:{bg};border-radius:10px;
                        padding:12px 14px;margin-bottom:12px;">
              <div style="font-size:1.1rem;font-weight:700;color:#1a6b6b;">
                {RANK_BADGES[i]} {RANK_LABELS[i]}
              </div>
              <div style="margin:6px 0;">{chips}</div>
              <div style="color:#374151;font-size:0.85rem;">{desc}</div>
              <div style="color:#1a6b6b;font-weight:600;margin-top:6px;">
                Resilience Score: {item["score"]}%
              </div>
              {active_note}
            </div>
            """,
            unsafe_allow_html=True,
        )


# ════════════════════════════════════════════════════════════════════════
# SECTION D — RESILIENCE RADAR CHART
# ════════════════════════════════════════════════════════════════════════

st.subheader("📈 Resilience Profile — With vs. Without Adaptations")

categories = [
    "Crop Yield Stability",
    "Water Security",
    "Groundwater Health",     # inverted groundwater_stress
    "Low Agricultural Risk",  # inverted agricultural_risk
    "Regional Resilience",
]

with_vals = [
    results["crop_yield_stability"],
    results["water_reservoir_security"],
    100 - results["groundwater_stress"],
    100 - (results["agricultural_risk"] / 5 * 100),
    results["regional_resilience"],
]

without_vals = [
    baseline["crop_yield_stability"],
    baseline["water_reservoir_security"],
    100 - baseline["groundwater_stress"],
    100 - (baseline["agricultural_risk"] / 5 * 100),
    baseline["regional_resilience"],
]

fig_radar = go.Figure()
fig_radar.add_trace(go.Scatterpolar(
    r=without_vals + [without_vals[0]],
    theta=categories + [categories[0]],
    fill="toself",
    name="Without Adaptations",
    line={"color": "#f97316", "dash": "dash"},
    fillcolor="rgba(249,115,22,0.1)",
))
fig_radar.add_trace(go.Scatterpolar(
    r=with_vals + [with_vals[0]],
    theta=categories + [categories[0]],
    fill="toself",
    name="With Current Adaptations",
    line={"color": "#0d9488"},
    fillcolor="rgba(13,148,136,0.15)",
))
fig_radar.update_layout(
    polar={
        "radialaxis": {"visible": True, "range": [0, 100], "ticksuffix": "%"},
        "angularaxis": {"rotation": 90},
    },
    showlegend=True,
    paper_bgcolor="rgba(0,0,0,0)",
    height=380,
    margin={"l": 40, "r": 40, "t": 40, "b": 40},
)
st.plotly_chart(fig_radar, use_container_width=True)


# ════════════════════════════════════════════════════════════════════════
# SECTION E — Z-SCORE GUIDANCE PANEL
# ════════════════════════════════════════════════════════════════════════

st.subheader("📐 Z-Score Risk Thresholds")

MOCK_STATS = {
    "crop_yield_stability":     {"mean": 72.0, "std": 12.0},
    "water_reservoir_security": {"mean": 68.0, "std": 10.0},
    "groundwater_stress":       {"mean": 35.0, "std": 15.0},
    "agricultural_risk":        {"mean": 2.1,  "std": 0.8},
    "regional_resilience":      {"mean": 65.0, "std": 11.0},
}

# Display name + whether positive Z = worse (reversed directive mapping).
ZSCORE_META = {
    "crop_yield_stability":     ("🌾 Crop Yield Stability", "%", False),
    "water_reservoir_security": ("💧 Water Reservoir Security", "%", False),
    "groundwater_stress":       ("🏜 Groundwater Stress", "%", True),
    "agricultural_risk":        ("⚠️ Agricultural Risk", "/ 5.0", True),
    "regional_resilience":      ("🛡 Regional Resilience", "%", False),
}


def _directive_for_z(z, reversed_dir):
    """Map a z-score to a policy directive. If reversed_dir, positive z = worse."""
    effective = -z if reversed_dir else z
    if effective < -2.0:
        return "🔴 Critical Drought Guidance — Emergency Response"
    elif effective < -1.0:
        return "🟠 Elevated Stress Protocol"
    elif effective < 0:
        return "🟡 Enhanced Monitoring Required"
    return "🟢 Normal Operating Range"


zscore_rows = []
for key, (display_name, unit, reversed_dir) in ZSCORE_META.items():
    value = results[key]
    stats = MOCK_STATS[key]
    z = calculate_zscore(value, stats["mean"], stats["std"])
    zscore_rows.append({
        "Indicator":     display_name,
        "Current Value": f"{value}{unit}",
        "Z-Score":       z,
        "Directive":     _directive_for_z(z, reversed_dir),
    })

zscore_df = pd.DataFrame(zscore_rows)
st.dataframe(zscore_df, use_container_width=True, hide_index=True)

st.caption(
    "Z-score indicates standard deviations from the 40-year historical mean. "
    "Values below −2.0 trigger emergency-level guidance from the policy "
    "knowledge base."
)


# ════════════════════════════════════════════════════════════════════════
# SECTION F — TRANSPARENCY & UNCERTAINTY EXPANDER
# ════════════════════════════════════════════════════════════════════════

with st.expander("🔍 Transparency & Model Confidence", expanded=False):
    t1, t2, t3 = st.columns(3)

    with t1:
        st.markdown("**📊 Confidence Ranges**")
        CONFIDENCE_RANGES = {
            "Crop Yield Stability":     {"value": results["crop_yield_stability"],
                                         "range": 12.0, "hist_mean": 72.0},
            "Water Reservoir Security": {"value": results["water_reservoir_security"],
                                         "range": 10.0, "hist_mean": 68.0},
            "Groundwater Stress":       {"value": results["groundwater_stress"],
                                         "range": 15.0, "hist_mean": 35.0},
            "Agricultural Risk":        {"value": results["agricultural_risk"],
                                         "range": 0.6,  "hist_mean": 2.1},
            "Regional Resilience":      {"value": results["regional_resilience"],
                                         "range": 11.0, "hist_mean": 65.0},
        }
        conf_df = pd.DataFrame([
            {
                "Indicator": name,
                "Estimate":  d["value"],
                "± Range":   d["range"],
                "Hist. Mean": d["hist_mean"],
            }
            for name, d in CONFIDENCE_RANGES.items()
        ])
        st.dataframe(conf_df, use_container_width=True, hide_index=True)

    with t2:
        st.markdown("**🤖 Model Information**")
        st.markdown(
            """
            - **Model:** Random Forest Regressor (Surrogate Emulator)
            - **Training period:** 1982–2022 (40 years)
            - **Features:** SST anomaly, Rainfall deficit,
              Drought duration, Heat stress, Policy flags
            - **Targets:** Crop Yield, Water Security
            - **Last updated:** June 2025
            - **Limitations:** Cannot account for sudden
              geopolitical or infrastructure shocks.
            """
        )

    with t3:
        st.markdown("**⚠️ Distribution Check**")
        ood = (
            st.session_state.sst_anomaly > 3.0
            or st.session_state.rainfall_deficit > 80
            or st.session_state.drought_months > 10
            or st.session_state.heat_stress == 5
        )
        if ood:
            st.error(
                "**Out-of-Distribution Scenario**  \n"
                "Parameters exceed historical training range.  \n"
                "Results are exploratory estimates only."
            )
        else:
            st.success(
                "✅ All parameters within historical training range (1982–2022)."
            )

        st.markdown(
            """
            **Data Coverage:**
            Region: South/Central Asia pilot zone
            Source: Historical climate + agricultural records
            Boundary: 1982–2022 daily observations
            """
        )


# ════════════════════════════════════════════════════════════════════════
# SECTION C — EXPORT ACTION BRIEFING
# ════════════════════════════════════════════════════════════════════════

st.divider()
st.subheader("📄 Export Action Briefing")

# Best-scoring combination becomes the recommended strategy in the report.
top = sorted(all_combos, key=lambda x: x["score"], reverse=True)[0]
top_strategy = {
    "strategies": [
        STRATEGY_NAMES[k] for k, v in top["combo"].items() if v
    ],
    "score": top["score"],
}

scenario_data = {
    "sst":        st.session_state.sst_anomaly,
    "rainfall":   st.session_state.rainfall_deficit,
    "drought":    st.session_state.drought_months,
    "heat":       st.session_state.heat_stress,
    "adapt_dict": adapt_dict,
}
ood = (
    st.session_state.sst_anomaly > 3.0
    or st.session_state.rainfall_deficit > 80
    or st.session_state.drought_months > 10
    or st.session_state.heat_stress == 5
)

txt_content = generate_txt_report(scenario_data, results, top_strategy, ood)

csv_df = pd.DataFrame([{
    "SST_Anomaly_C":        st.session_state.sst_anomaly,
    "Rainfall_Deficit_pct": st.session_state.rainfall_deficit,
    "Drought_Months":       st.session_state.drought_months,
    "Heat_Stress":          st.session_state.heat_stress,
    "Crop_Yield_Stability": results["crop_yield_stability"],
    "Water_Security":       results["water_reservoir_security"],
    "Groundwater_Stress":   results["groundwater_stress"],
    "Agricultural_Risk":    results["agricultural_risk"],
    "Regional_Resilience":  results["regional_resilience"],
}])

exp_col1, exp_col2, exp_col3 = st.columns(3)

with exp_col1:
    st.download_button(
        label="⬇ Download TXT Report",
        data=txt_content,
        file_name="climate_resilience_briefing.txt",
        mime="text/plain",
        use_container_width=True,
    )

with exp_col2:
    try:
        pdf_bytes = generate_pdf_report(
            scenario_data, results, top_strategy, ood
        )
        st.download_button(
            label="⬇ Download PDF Report",
            data=pdf_bytes,
            file_name="climate_resilience_briefing.pdf",
            mime="application/pdf",
            use_container_width=True,
        )
    except ImportError:
        st.info("PDF export requires: pip install fpdf2")

with exp_col3:
    st.download_button(
        label="⬇ Download CSV Data",
        data=csv_df.to_csv(index=False),
        file_name="climate_scenario_data.csv",
        mime="text/csv",
        use_container_width=True,
    )


# ════════════════════════════════════════════════════════════════════════
# SECTION E — FOOTER
# ════════════════════════════════════════════════════════════════════════

st.divider()
st.markdown(
    """
    <div style="text-align:center;color:#9ca3af;font-size:0.78rem;
                padding:16px 0 8px 0;">
      🌍 <strong>AI Climate Resilience Sandbox</strong> &nbsp;·&nbsp;
      SDG 13: Climate Action &nbsp;·&nbsp;
      Built for Hackathon MVP &nbsp;·&nbsp;
      <em>Not an operational forecast tool</em>
    </div>
    """,
    unsafe_allow_html=True,
)
